[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
farmtrace = "FwtvuwpaD8vnDttYg6h8x8bugkm47fuwoNKd9tfF7sCE"

[programs.devnet]
farmtrace = "FwtvuwpaD8vnDttYg6h8x8bugkm47fuwoNKd9tfF7sCE"

[programs.mainnet]
farmtrace = "FwtvuwpaD8vnDttYg6h8x8bugkm47fuwoNKd9tfF7sCE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000